# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hShNWhV-bBvri6ZmXuUviicNHvBlJ6Fd
"""

import matplotlib.pyplot as plt
import numpy as np

# Define the parameter t
t = np.linspace(0, 2 * np.pi, 1000)

# Parametric equations for the heart shape
x = 16 * np.sin(t)**3
y = 13 * np.cos(t) - 5 * np.cos(2*t) - 2 * np.cos(3*t) - np.cos(4*t)

# Plot the heart shape using the generated x and y arrays
plt.plot(x, y, color='red')
plt.fill(x, y, color='red', alpha=0.6)  # Fill the heart shape with color
plt.title("Heart Shape Plot")
plt.axis('equal')  # Equal aspect ratio ensures the heart is not distorted
plt.axis('off')  # Turn off axis for better visualization
plt.show()

# Print x and y as arrays
print("x =", x)
print("y =", y)



import matplotlib.pyplot as plt
import numpy as np

x=np.array([0, 20, 7, 9, 10, 13, 15, 17, 21, 23])
y=np.array([10, 30, 5, 11, 16, 14, 16, 19, 23, 25 ])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([4, 9, 12, 15])

plt.plot(x,marker='o')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([4, 9, 12, 15])

plt.plot(x,'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([3,2, 8, 1, 12])

plt.plot(x,'o:b', ms=20)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation

def draw_stick_figure(ax, x, y, angle):
    head_radius = 1
    head = plt.Circle((x, y + 5), head_radius, color='black', fill=False)

    body_x = [x, x]
    body_y = [y + 3, y + 2]
    ax.plot(body_x, body_y, color='black')
    leg1_x = [x, x + np.sin(angle)]
    leg1_y = [y + 2, y + 0.5]
    ax.plot(leg1_x, leg1_y, color='black')

    leg2_x = [x, x - np.sin(angle)]
    leg2_y = [y + 2, y + 0.5]
    ax.plot(leg2_x, leg2_y, color='black')

    arm1_x = [x, x + np.cos(angle) * 2]
    arm1_y = [y + 3, y + 4]
    ax.plot(arm1_x, arm1_y, color='black')

    arm2_x = [x, x - np.cos(angle) * 2]
    arm2_y = [y + 3, y + 4]
    ax.plot(arm2_x, arm2_y, color='black')

    ax.add_patch(head)

fig, ax = plt.subplots()
ax.set_xlim(-10, 110)
ax.set_ylim(-5, 15)
ax.set_aspect('equal')
ax.axis('off')

def update(frame):
    ax.clear()
    ax.set_xlim(-10, 110)
    ax.set_ylim(-5, 15)
    ax.set_aspect('equal')
    ax.axis('off')


    draw_stick_figure(ax, x=frame, y=5, angle=np.sin(frame * 0.2))

ani = FuncAnimation(fig, update, frames=np.arange(0, 100, 0.5), interval=50)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,1, 2, 3])
y1=np.array([3,8, 1, 10])
x2=np.array([0,1, 2, 3])
y2=np.array([6,2, 7, 11])

plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,1, 2, 3,4,5])
y1=np.array([0,8, 12, 20, 26,38])

plt.plot(x1,y1)
plt.xlabel("Overs")
plt.ylabel("Runs")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,1, 2, 3,4,5])
y1=np.array([0,8, 12, 20, 26,38])


plt.plot(x1,y1)
plt.xlabel("Overs")
plt.ylabel("Runs")
plt.title("Sport Data", loc='left')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,1, 2, 3,4,5])
y1=np.array([0,8, 12, 20, 26,38])


plt.scatter(x1,y1)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1, 2, 3,4,5])
y=np.array([0,2, 8, 1, 14,7])
plt.scatter(x,y, color='blue')

x=np.array([12,6, 8, 11,8,5])
y=np.array([5,6, 3, 7, 17,19])
plt.scatter(x,y, color='red')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1, 2, 3,4,5])
y=np.array([0,2, 8, 1, 14,7])
mycolor=['blue', 'green','purple', 'aqua', 'yellow', 'lime']
plt.scatter(x,y, color=mycolor)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1, 2, 3,4,5])
y=np.array([0,2, 8, 1, 14,7])
mycolor=['blue', 'green','purple', 'aqua', 'yellow', 'lime']
size=[10,60,70,80,80,120]
plt.scatter(x,y, color=mycolor,s=size)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['A','B','C','D',])
y=np.array([3,8,  1, 10])
plt.bar(x,y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['A','B','C','D',])
y=np.array([3,8,  1, 10])
plt.barh(x,y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
plt.pie(y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(y, labels=mylabels)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(y, labels=mylabels, startangle=90)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode=[0.2,0,0,0]
plt.pie(y, labels=mylabels, startangle=90, explode=myexplode)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode=[0.2,0,0,0]
plt.pie(y, labels=mylabels, startangle=90, explode=myexplode, shadow=True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode=[0.2,0,0,0]
mycolors=['black', 'hotpink', 'b', '#4CAF50']
plt.pie(y, labels=mylabels, startangle=90, explode=myexplode, shadow=True, colors=mycolors)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]

plt.pie(y, labels=mylabels)
plt.legend()

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]

plt.pie(y, labels=mylabels)
plt.legend(title='fOUR FRUITS')

plt.show()